Repository neo-project/neo-devpack-dotnet, pull requests merged in 2024-02, with the labels that each got.

#882 [Compiler] move expressions out of convert file.
  src/Neo.Compiler.CSharp/MethodConvert/Expression/AnonymousObjectCreationExpression.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/ArrayCreationExpression.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/AssignmentExpression.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/BinaryExpression.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/CastExpression.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/CheckedExpression.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/ConditionalAccessExpression.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/ConditionalExpression.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/ElementExpression.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/IdentifierNameExpression.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/ImplicitArrayCreationExpression.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/InitializerExpression.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/InterpolatedStringExpression.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/InvocationExpression.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/IsPatternExpression.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/MemberExpression.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/ObjectCreationExpression.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/SwitchExpression.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/TupleExpression.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/UnaryExpression.cs
  src/Neo.Compiler.CSharp/MethodConvert/MethodConvert.cs
Labels: waiting for review

#891 Update and fix Nep17 template
  src/Neo.SmartContract.Template/templates/neocontractnep17/Contract1.cs
Labels: waiting for review

#890 new Testing environment
  neo-devpack-dotnet.sln
  src/Neo.Compiler.CSharp/Neo.Compiler.CSharp.csproj
  src/Neo.Compiler.CSharp/Options.cs
  src/Neo.Compiler.CSharp/Program.cs
  src/Neo.SmartContract.Testing/CustomMock.cs
  src/Neo.SmartContract.Testing/Extensions/ArtifactExtensions.cs
  src/Neo.SmartContract.Testing/Extensions/MockExtensions.cs
  src/Neo.SmartContract.Testing/Extensions/TestExtensions.cs
  src/Neo.SmartContract.Testing/Native/ContractManagement.cs
  src/Neo.SmartContract.Testing/Native/CryptoLib.cs
  src/Neo.SmartContract.Testing/Native/GasToken.cs
  src/Neo.SmartContract.Testing/Native/LedgerContract.cs
  src/Neo.SmartContract.Testing/Native/NeoToken.cs
  src/Neo.SmartContract.Testing/Native/OracleContract.cs
  src/Neo.SmartContract.Testing/Native/PolicyContract.cs
  src/Neo.SmartContract.Testing/Native/RoleManagement.cs
  src/Neo.SmartContract.Testing/Native/StdLib.cs
  src/Neo.SmartContract.Testing/NativeArtifacts.cs
  src/Neo.SmartContract.Testing/Neo.SmartContract.Testing.csproj
  src/Neo.SmartContract.Testing/README.md
  src/Neo.SmartContract.Testing/SmartContract.cs
  src/Neo.SmartContract.Testing/SmartContractInitialize.cs
  src/Neo.SmartContract.Testing/SmartContractStorage.cs
  src/Neo.SmartContract.Testing/TestEngine.cs
  src/Neo.SmartContract.Testing/TestStorage.cs
  src/Neo.SmartContract.Testing/TestingApplicationEngine.cs
  tests/Neo.SmartContract.Testing.UnitTests/Extensions/ArtifactExtensionsTests.cs
  tests/Neo.SmartContract.Testing.UnitTests/NativeArtifactsTests.cs
  tests/Neo.SmartContract.Testing.UnitTests/Neo.SmartContract.Testing.UnitTests.csproj
  tests/Neo.SmartContract.Testing.UnitTests/SmartContractStorageTests.cs
  tests/Neo.SmartContract.Testing.UnitTests/TestEngineTests.cs
  tests/Neo.SmartContract.Testing.UnitTests/TestStorageTests.cs
Labels: blocker, waiting for review

#895 bug: Fix default value when Stored
  src/Neo.Compiler.CSharp/MethodConvert/MethodConvert.cs
  tests/Neo.SmartContract.Framework.TestContracts/Contract_Stored.cs
  tests/Neo.SmartContract.Framework.UnitTests/Services/BackedStorageTest.cs
Labels: bug, blocker, waiting for review, breaking-change

#899 Added `publish` to `github packages` and fix submodules
  .github/workflows/main.yml
  .github/workflows/pkgs-delete.yml
  NuGet.Config
Labels: waiting for review

#898 TestEngine: Get instruction coverage and move to net standard
  src/Neo.SmartContract.Testing/Coverage/AbiMethod.cs
  src/Neo.SmartContract.Testing/Coverage/CoverageBase.cs
  src/Neo.SmartContract.Testing/Coverage/CoverageHit.cs
  src/Neo.SmartContract.Testing/Coverage/CoveredCollection.cs
  src/Neo.SmartContract.Testing/Coverage/CoveredContract.cs
  src/Neo.SmartContract.Testing/Coverage/CoveredMethod.cs
  src/Neo.SmartContract.Testing/CustomMock.cs
  src/Neo.SmartContract.Testing/Extensions/ArtifactExtensions.cs
  src/Neo.SmartContract.Testing/Extensions/SmartContractExtensions.cs
  src/Neo.SmartContract.Testing/Neo.SmartContract.Testing.csproj
  src/Neo.SmartContract.Testing/README.md
  src/Neo.SmartContract.Testing/SmartContractInitialize.cs
  src/Neo.SmartContract.Testing/TestEngine.cs
  src/Neo.SmartContract.Testing/TestingApplicationEngine.cs
  tests/Neo.SmartContract.Testing.UnitTests/Coverage/CoverageDataTests.cs
  tests/Neo.SmartContract.Testing.UnitTests/Extensions/ArtifactExtensionsTests.cs
  tests/Neo.SmartContract.Testing.UnitTests/NativeArtifactsTests.cs
Labels: waiting for review

#903 [Framework Add] predefine manifest
  src/Neo.Compiler.CSharp/CompilationContext.cs
  src/Neo.SmartContract.Framework/Attributes/AuthorAttribute.cs
  src/Neo.SmartContract.Framework/Attributes/DescriptionAttribute.cs
  src/Neo.SmartContract.Framework/Attributes/EmailAttribute.cs
  src/Neo.SmartContract.Framework/Attributes/ManifestExtraAttribute.cs
  src/Neo.SmartContract.Framework/Attributes/VersionAttribute.cs
  tests/Neo.SmartContract.Framework.TestContracts/Contract_ManifestAttribute.cs
  tests/Neo.SmartContract.Framework.UnitTests/ManifestAttributeTest.cs
Labels: waiting for review

#907 Basic devcontainer
  .devcontainer/devcontainer.json
  .vscode/settings.json
Labels: waiting for review

#893 Nep17 UnitTests
  .github/workflows/main.yml
  neo-devpack-dotnet.sln
  src/Neo.Compiler.CSharp/Neo.Compiler.CSharp.csproj
  src/Neo.Compiler.CSharp/Options.cs
  src/Neo.Compiler.CSharp/Program.cs
  src/Neo.SmartContract.Template/templates/neocontractnep17/.template.config/template.json
  src/Neo.SmartContract.Template/templates/neocontractnep17/Nep17Contract.cs
  src/Neo.SmartContract.Template/templates/neocontractnep17/Nep17Contract.csproj
  src/Neo.SmartContract.Testing/Coverage/CoverageBase.cs
  src/Neo.SmartContract.Testing/Coverage/CoveredContract.cs
  src/Neo.SmartContract.Testing/Coverage/CoveredMethod.cs
  src/Neo.SmartContract.Testing/Extensions/ArtifactExtensions.cs
  src/Neo.SmartContract.Testing/Extensions/StandardExtensions.cs
  src/Neo.SmartContract.Testing/Extensions/TestExtensions.cs
  src/Neo.SmartContract.Testing/InvalidTypes/InvalidUInt160.cs
  src/Neo.SmartContract.Testing/InvalidTypes/InvalidUInt256.cs
  src/Neo.SmartContract.Testing/Native/ContractManagement.cs
  src/Neo.SmartContract.Testing/Native/CryptoLib.cs
  src/Neo.SmartContract.Testing/Native/GasToken.cs
  src/Neo.SmartContract.Testing/Native/LedgerContract.cs
  src/Neo.SmartContract.Testing/Native/NeoToken.cs
  src/Neo.SmartContract.Testing/Native/OracleContract.cs
  src/Neo.SmartContract.Testing/Native/PolicyContract.cs
  src/Neo.SmartContract.Testing/Native/RoleManagement.cs
  src/Neo.SmartContract.Testing/Native/StdLib.cs
  src/Neo.SmartContract.Testing/NativeArtifacts.cs
  src/Neo.SmartContract.Testing/Neo.SmartContract.Testing.csproj
  src/Neo.SmartContract.Testing/README.md
  src/Neo.SmartContract.Testing/SmartContract.cs
  src/Neo.SmartContract.Testing/TestEngine.cs
  src/Neo.SmartContract.Testing/TestingApplicationEngine.cs
  src/Neo.SmartContract.Testing/TestingStandards/INep17Standard.cs
  src/Neo.SmartContract.Testing/TestingStandards/IOwnable.cs
  src/Neo.SmartContract.Testing/TestingStandards/IVerificable.cs
  src/Neo.SmartContract.Testing/TestingStandards/Nep17Tests.cs
  src/Neo.SmartContract.Testing/TestingStandards/OwnableTests.cs
  src/Neo.SmartContract.Testing/TestingStandards/TestBase.cs
  tests/Neo.SmartContract.Template.UnitTests/Neo.SmartContract.Template.UnitTests.csproj
  tests/Neo.SmartContract.Template.UnitTests/templates/neocontractnep17/CoverageContractTests.cs
  tests/Neo.SmartContract.Template.UnitTests/templates/neocontractnep17/Nep17ContractTests.cs
  tests/Neo.SmartContract.Template.UnitTests/templates/neocontractnep17/OwnerContractTests.cs
  tests/Neo.SmartContract.Testing.UnitTests/Coverage/CoverageDataTests.cs
  tests/Neo.SmartContract.Testing.UnitTests/Extensions/ArtifactExtensionsTests.cs
  tests/Neo.SmartContract.Testing.UnitTests/Extensions/TestExtensionsTests.cs
  tests/Neo.SmartContract.Testing.UnitTests/NativeArtifactsTests.cs
  tests/Neo.SmartContract.Testing.UnitTests/TestEngineTests.cs
Labels: help wanted, blocked

#904 TestEngine: add Checkpoints, RpcStorage and Dump to html
  src/Neo.Compiler.CSharp/Options.cs
  src/Neo.Compiler.CSharp/Program.cs
  src/Neo.SmartContract.Testing/Coverage/AbiMethod.cs
  src/Neo.SmartContract.Testing/Coverage/CoverageHit.cs
  src/Neo.SmartContract.Testing/Coverage/CoveredContract.cs
  src/Neo.SmartContract.Testing/Coverage/CoveredMethod.cs
  src/Neo.SmartContract.Testing/Coverage/DumpFormat.cs
  src/Neo.SmartContract.Testing/Extensions/TestExtensions.cs
  src/Neo.SmartContract.Testing/README.md
  src/Neo.SmartContract.Testing/SmartContract.cs
  src/Neo.SmartContract.Testing/Storage/EngineCheckpoint.cs
  src/Neo.SmartContract.Testing/Storage/EngineStorage.cs
  src/Neo.SmartContract.Testing/Storage/Rpc/RpcSnapshot.cs
  src/Neo.SmartContract.Testing/Storage/Rpc/RpcStore.cs
  src/Neo.SmartContract.Testing/TestEngine.cs
  src/Neo.SmartContract.Testing/TestingApplicationEngine.cs
  src/Neo.SmartContract.Testing/TestingStandards/Nep17Tests.cs
  tests/Neo.SmartContract.Template.UnitTests/templates/neocontractnep17/CoverageContractTests.cs
  tests/Neo.SmartContract.Template.UnitTests/templates/neocontractnep17/Nep17ContractTests.cs
  tests/Neo.SmartContract.Template.UnitTests/templates/neocontractnep17/OwnerContractTests.cs
  tests/Neo.SmartContract.Testing.UnitTests/Coverage/CoverageDataTests.cs
  tests/Neo.SmartContract.Testing.UnitTests/Extensions/ArtifactExtensionsTests.cs
  tests/Neo.SmartContract.Testing.UnitTests/Storage/Rpc/RpcStoreTests.cs
  tests/Neo.SmartContract.Testing.UnitTests/Storage/TestStorageTests.cs
Labels: waiting for review

#919 Update pkgs-delete.yml
  .github/workflows/pkgs-delete.yml
Labels: critical

#921 Fix: compilation and coverage issues
  NuGet.Config
  src/Neo.Compiler.CSharp/CompilationContext.cs
  src/Neo.SmartContract.Testing/Coverage/CoverageHit.cs
  src/Neo.SmartContract.Testing/Coverage/CoveredContract.cs
  src/Neo.SmartContract.Testing/Coverage/MethodDetectionMechanism.cs
  src/Neo.SmartContract.Testing/Extensions/TestExtensions.cs
  src/Neo.SmartContract.Testing/SmartContract.cs
  src/Neo.SmartContract.Testing/SmartContractStorage.cs
  src/Neo.SmartContract.Testing/TestEngine.cs
  src/Neo.SmartContract.Testing/TestingApplicationEngine.cs
  src/Neo.SmartContract.Testing/TestingStandards/Nep17Tests.cs
Labels: waiting for review

#934 TestEngine: Some fixes in TestEngine
  src/Neo.SmartContract.Testing/Attributes/FieldOrderAttribute.cs
  src/Neo.SmartContract.Testing/Extensions/TestExtensions.cs
  src/Neo.SmartContract.Testing/Native/ContractManagement.cs
  src/Neo.SmartContract.Testing/Native/CryptoLib.cs
  src/Neo.SmartContract.Testing/Native/GasToken.cs
  src/Neo.SmartContract.Testing/Native/LedgerContract.cs
  src/Neo.SmartContract.Testing/Native/NeoToken.cs
  src/Neo.SmartContract.Testing/Native/OracleContract.cs
  src/Neo.SmartContract.Testing/Native/PolicyContract.cs
  src/Neo.SmartContract.Testing/Native/RoleManagement.cs
  src/Neo.SmartContract.Testing/Native/StdLib.cs
  src/Neo.SmartContract.Testing/NativeArtifacts.cs
  src/Neo.SmartContract.Testing/Storage/EngineStorage.cs
  src/Neo.SmartContract.Testing/TestEngine.cs
  src/Neo.SmartContract.Testing/TestingApplicationEngine.cs
  tests/Neo.SmartContract.Testing.UnitTests/Extensions/TestExtensionsTests.cs
  tests/Neo.SmartContract.Testing.UnitTests/Neo.SmartContract.Testing.UnitTests.csproj
  tests/Neo.SmartContract.Testing.UnitTests/TestEngineTests.cs
Labels: waiting for review

#936 TestEngine: Compute coverage branches
  src/Neo.SmartContract.Testing/Coverage/CoverageBase.cs
  src/Neo.SmartContract.Testing/Coverage/CoverageBranch.cs
  src/Neo.SmartContract.Testing/Coverage/CoveredCollection.cs
  src/Neo.SmartContract.Testing/Coverage/CoveredContract.cs
  src/Neo.SmartContract.Testing/Coverage/CoveredMethod.cs
  src/Neo.SmartContract.Testing/TestEngine.cs
  src/Neo.SmartContract.Testing/TestingApplicationEngine.cs
  tests/Neo.SmartContract.Template.UnitTests/templates/neocontractnep17/CoverageContractTests.cs
  tests/Neo.SmartContract.Testing.UnitTests/Coverage/CoverageDataTests.cs
  tests/Neo.SmartContract.Testing.UnitTests/NativeArtifactsTests.cs
Labels: waiting for review

#937 TestEngine: Source code coverage
  .github/workflows/main.yml
  src/Neo.SmartContract.Testing/Coverage/CoverageBase.cs
  src/Neo.SmartContract.Testing/Coverage/CoverageReporting.cs
  src/Neo.SmartContract.Testing/Coverage/CoveredContract.cs
  src/Neo.SmartContract.Testing/Coverage/Formats/CoberturaFormat.ContractCoverageWriter.cs
  src/Neo.SmartContract.Testing/Coverage/Formats/CoberturaFormat.cs
  src/Neo.SmartContract.Testing/Coverage/Formats/ConsoleFormat.cs
  src/Neo.SmartContract.Testing/Coverage/Formats/ICoverageFormat.cs
  src/Neo.SmartContract.Testing/Coverage/Formats/IntructionHtmlFormat.cs
  src/Neo.SmartContract.Testing/Coverage/NeoDebugInfo.Internals.cs
  src/Neo.SmartContract.Testing/Coverage/NeoDebugInfo.cs
  src/Neo.SmartContract.Testing/Neo.SmartContract.Testing.csproj
  tests/Directory.Build.props
  tests/Neo.SmartContract.Template.UnitTests/Neo.SmartContract.Template.UnitTests.csproj
  tests/Neo.SmartContract.Template.UnitTests/templates/neocontractnep17/CoverageContractTests.cs
  tests/Neo.SmartContract.Testing.UnitTests/NativeArtifactsTests.cs
Labels: waiting for review

#941 TestEngine: Fix some snapshots problems
  src/Neo.SmartContract.Testing/README.md
  src/Neo.SmartContract.Testing/Storage/EngineCheckpoint.cs
  src/Neo.SmartContract.Testing/Storage/EngineStorage.cs
  src/Neo.SmartContract.Testing/TestEngine.cs
  src/Neo.SmartContract.Testing/TestingApplicationEngine.cs
  src/Neo.SmartContract.Testing/TestingStandards/Nep17Tests.cs
  tests/Neo.SmartContract.Template.UnitTests/templates/neocontractnep17/CoverageContractTests.cs
Labels: waiting for review

#938 Fix `if` statement sequence points and `SequencePointInserter`
  src/Neo.Compiler.CSharp/CompilationContext.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/Expression.cs
  src/Neo.Compiler.CSharp/MethodConvert/SourceConvert.cs
  src/Neo.Compiler.CSharp/MethodConvert/Statement/DoStatement.cs
  src/Neo.Compiler.CSharp/MethodConvert/Statement/ExpressionStatement.cs
  src/Neo.Compiler.CSharp/MethodConvert/Statement/ForStatement.cs
  src/Neo.Compiler.CSharp/MethodConvert/Statement/IfStatement.cs
  src/Neo.Compiler.CSharp/SequencePointInserter.cs
  src/Neo.SmartContract.Testing/Coverage/CoverageReporting.cs
  src/Neo.SmartContract.Testing/Coverage/Formats/CoberturaFormat.ContractCoverageWriter.cs
  src/Neo.SmartContract.Testing/Coverage/Formats/CoberturaFormat.cs
  src/Neo.SmartContract.Testing/TestingStandards/Nep17Tests.cs
  tests/Neo.Compiler.CSharp.UnitTests/UnitTest_DebugInfo.cs
  tests/Neo.SmartContract.Framework.TestContracts/Contract_SequencePointInserter.cs
  tests/Neo.SmartContract.Framework.UnitTests/Services/SequencePointInserterTest.cs
Labels: bug, waiting for review

#942 TestEngine: Fix branch %
  src/Neo.SmartContract.Testing/Coverage/CoverageBase.cs
  src/Neo.SmartContract.Testing/Coverage/CoverageBranch.cs
Labels: waiting for review

#943 Fix coverage
  .github/workflows/main.yml
Labels: waiting for review

#944 TestEngine: Allow to change the caller
  src/Neo.SmartContract.Testing/README.md
  src/Neo.SmartContract.Testing/TestEngine.cs
  src/Neo.SmartContract.Testing/TestingApplicationEngine.cs
  tests/Neo.SmartContract.Testing.UnitTests/TestEngineTests.cs
Labels: waiting for review

#947 Remove neocontract template
  src/Neo.SmartContract.Template/templates/neocontract/.config/dotnet-tools.json
  src/Neo.SmartContract.Template/templates/neocontract/.template.config/icon.png
  src/Neo.SmartContract.Template/templates/neocontract/.template.config/template.json
  src/Neo.SmartContract.Template/templates/neocontract/Contract1.cs
  src/Neo.SmartContract.Template/templates/neocontract/ProjectName.csproj
Labels: waiting for review

#946 TestEngine changes
  src/Neo.SmartContract.Testing/InvalidTypes/InvalidUInt160.cs
  src/Neo.SmartContract.Testing/InvalidTypes/InvalidUInt256.cs
  src/Neo.SmartContract.Testing/README.md
  src/Neo.SmartContract.Testing/SmartContract.cs
  src/Neo.SmartContract.Testing/Storage/SmartContractStorage.cs
  src/Neo.SmartContract.Testing/TestEngine.cs
  src/Neo.SmartContract.Testing/TestingApplicationEngine.cs
  src/Neo.SmartContract.Testing/TestingStandards/Nep17Tests.cs
  src/Neo.SmartContract.Testing/TestingStandards/OwnableTests.cs
  tests/Neo.SmartContract.Template.UnitTests/templates/neocontractnep17/Nep17ContractTests.cs
  tests/Neo.SmartContract.Testing.UnitTests/Storage/TestStorageTests.cs
  tests/Neo.SmartContract.Testing.UnitTests/TestEngineTests.cs
Labels: waiting for review

#908 [Compiler Add] allow multiple smart contract exist in one project
  src/Neo.Compiler.CSharp/CompilationContext.cs
  src/Neo.Compiler.CSharp/CompilationEngine.cs
  src/Neo.Compiler.CSharp/MethodConvert/CallHelpers.cs
  src/Neo.Compiler.CSharp/MethodConvert/ConstructorConvert.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/AssignmentExpression.CoalesceAssignment.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/AssignmentExpression.ComplexAssignment.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/AssignmentExpression.SimpleAssignment.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/IdentifierNameExpression.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/MemberExpression.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/ObjectCreationExpression.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/UnaryExpression.PostfixUnary.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/UnaryExpression.PrefixUnary.cs
  src/Neo.Compiler.CSharp/MethodConvert/ExternConvert.cs
  src/Neo.Compiler.CSharp/MethodConvert/MethodConvert.cs
  src/Neo.Compiler.CSharp/MethodConvert/PropertyConvert.cs
  src/Neo.Compiler.CSharp/Program.cs
  tests/Neo.Compiler.CSharp.TestContracts/Contract_Multiple.cs
  tests/Neo.Compiler.CSharp.UnitTests/UnitTest1.cs
  tests/Neo.SmartContract.Framework.UnitTests/Neo.SmartContract.Framework.UnitTests.csproj
  tests/Neo.SmartContract.TestEngine/TestEngine.cs
Labels: blocker, waiting for review

#952 [Framework] add interfaces
  src/Neo.Compiler.CSharp/CompilationEngine.cs
  src/Neo.SmartContract.Framework/Interfaces/INEP11Payment.cs
  src/Neo.SmartContract.Framework/Interfaces/INEP17Payment.cs
  tests/Neo.SmartContract.Framework.TestContracts/Contract_SupportedStandard11Enum.cs
  tests/Neo.SmartContract.Framework.TestContracts/Contract_SupportedStandard17Enum.cs
Labels: waiting for review

#796 Regex: add couple of regex methods to the devpack
  src/Neo.SmartContract.Framework/ByteString.Extension.cs
  tests/Neo.SmartContract.Framework.TestContracts/Contract_Regex.cs
  tests/Neo.SmartContract.Framework.UnitTests/RegexTest.cs
  tests/Neo.SmartContract.Framework.UnitTests/Services/ContractTest.cs
  tests/Neo.SmartContract.Template.UnitTests/templates/neocontractoracle/OracleRequestTests.cs
Labels: waiting for review

#958 Allow to compile a cs files without a project
  src/Neo.Compiler.CSharp/CompilationEngine.cs
Labels: blocker, waiting for review

#959 [Compiler Fix + Framework Add] add oracle interface and fix issue
  src/Neo.Compiler.CSharp/CompilationContext.cs
  src/Neo.Compiler.CSharp/CompilationEngine.cs
  src/Neo.SmartContract.Framework/Interfaces/IOracle.cs
  tests/Neo.SmartContract.Framework.TestContracts/Contract_IOracle.cs
  tests/Neo.SmartContract.Framework.UnitTests/Services/OracleTest.cs
Labels: waiting for review

#956 TestEngine: Template testing optimization
  .github/workflows/main.yml
  src/Neo.Compiler.CSharp/CompilationContext.cs
  src/Neo.Compiler.CSharp/CompilationEngine.cs
  src/Neo.Compiler.CSharp/CompilationOptions.cs
  src/Neo.Compiler.CSharp/Helper.cs
  src/Neo.Compiler.CSharp/MethodConvert/Expression/Expression.cs
  src/Neo.Compiler.CSharp/Options.cs
  src/Neo.Compiler.CSharp/Program.cs
  src/Neo.SmartContract.Framework/ContractParameterType.cs
  src/Neo.SmartContract.Framework/ECPoint.cs
  src/Neo.SmartContract.Framework/Native/CalledByGroupCondition.cs
  src/Neo.SmartContract.Framework/Native/CryptoLib.cs
  src/Neo.SmartContract.Framework/Native/GroupCondition.cs
  src/Neo.SmartContract.Framework/Native/NEO.cs
  src/Neo.SmartContract.Framework/Native/NeoAccountState.cs
  src/Neo.SmartContract.Framework/Native/RoleManagement.cs
  src/Neo.SmartContract.Framework/Native/Signer.cs
  src/Neo.SmartContract.Framework/Services/Contract.cs
  src/Neo.SmartContract.Framework/Services/ContractGroup.cs
  src/Neo.SmartContract.Framework/Services/Crypto.cs
  src/Neo.SmartContract.Framework/Services/Runtime.cs
  src/Neo.SmartContract.Framework/Services/StorageMap.cs
  src/Neo.SmartContract.Framework/UInt160.cs
  src/Neo.SmartContract.Framework/UInt256.cs
  src/Neo.SmartContract.Template/templates/neocontractnep17/.template.config/template.json
  src/Neo.SmartContract.Template/templates/neocontractnep17/Nep17Contract.cs
  src/Neo.SmartContract.Template/templates/neocontractoracle/.template.config/template.json
  src/Neo.SmartContract.Template/templates/neocontractoracle/OracleRequest.cs
  src/Neo.SmartContract.Template/templates/neocontractowner/.template.config/template.json
  src/Neo.SmartContract.Template/templates/neocontractowner/Ownable.cs
  src/Neo.SmartContract.Testing/Coverage/CoveredCollection.cs
  src/Neo.SmartContract.Testing/Coverage/CoveredContract.cs
  src/Neo.SmartContract.Testing/Coverage/CoveredMethod.cs
  src/Neo.SmartContract.Testing/Coverage/Formats/ConsoleFormat.cs
  src/Neo.SmartContract.Testing/Extensions/ArtifactExtensions.cs
  src/Neo.SmartContract.Testing/Extensions/MockExtensions.cs
  tests/Neo.Compiler.CSharp.TestContracts/Contract_Foreach.cs
  tests/Neo.Compiler.CSharp.TestContracts/Contract_Interfaces.cs
  tests/Neo.Compiler.CSharp.TestContracts/Contract_NativeContracts.cs
  tests/Neo.Compiler.CSharp.TestContracts/Contract_ParameterType.cs
  tests/Neo.Compiler.CSharp.TestContracts/Contract_StaticVar.cs
  tests/Neo.Compiler.CSharp.TestContracts/Contract_TryCatch.cs
  tests/Neo.Compiler.CSharp.TestContracts/Contract_Types_ECPoint.cs
  tests/Neo.SmartContract.Framework.TestContracts/Contract_Contract.cs
  tests/Neo.SmartContract.Framework.TestContracts/Contract_Crypto.cs
  tests/Neo.SmartContract.Framework.TestContracts/Contract_Native.cs
  tests/Neo.SmartContract.Framework.TestContracts/Contract_Storage.cs
  tests/Neo.SmartContract.Template.UnitTests/Neo.SmartContract.Template.UnitTests.csproj
  tests/Neo.SmartContract.Template.UnitTests/templates/CoverageContractTests.cs
  tests/Neo.SmartContract.Template.UnitTests/templates/TestCleanup.cs
  tests/Neo.SmartContract.Template.UnitTests/templates/neocontractnep17/Nep17ContractTests.cs
  tests/Neo.SmartContract.Template.UnitTests/templates/neocontractnep17/OwnerContractTests.cs
  tests/Neo.SmartContract.Template.UnitTests/templates/neocontractnep17/TestingArtifacts/Nep17ContractTemplate.artifacts.cs
  tests/Neo.SmartContract.Template.UnitTests/templates/neocontractoracle/OracleRequestTests.cs
  tests/Neo.SmartContract.Template.UnitTests/templates/neocontractoracle/TestingArtifacts/OracleRequestTemplate.artifacts.cs
  tests/Neo.SmartContract.Template.UnitTests/templates/neocontractowner/OwnableContractTests.cs
  tests/Neo.SmartContract.Template.UnitTests/templates/neocontractowner/TestingArtifacts/OwnableTemplate.artifacts.cs
Labels: waiting for review

#960 Fix optimizations using `CompilationEngine`
  src/Neo.Compiler.CSharp/CompilationContext.cs
  src/Neo.Compiler.CSharp/Optimizer/Strategies/Reachability.cs
  src/Neo.Compiler.CSharp/Program.cs
  tests/Neo.SmartContract.Template.UnitTests/templates/TestCleanup.cs
Labels: waiting for review

#964 Allow to choose the kind of optimization
  src/Neo.Compiler.CSharp/CompilationContext.cs
  src/Neo.Compiler.CSharp/CompilationOptions.cs
  src/Neo.Compiler.CSharp/MethodConvert/MethodConvert.cs
  src/Neo.Compiler.CSharp/Options.cs
  src/Neo.Compiler.CSharp/Program.cs
  tests/Neo.SmartContract.Template.UnitTests/templates/TestCleanup.cs
  tests/Neo.SmartContract.TestEngine/TestEngine.cs
Labels: waiting for review

#963 TestEngine: Merge smart contract coverage with coverlet
  .github/workflows/main.yml
  src/Neo.Compiler.CSharp/CompilationEngine.cs
  src/Neo.Compiler.CSharp/CompilationSourceReferences.cs
  src/Neo.Compiler.CSharp/MethodConvert/ExternConvert.cs
  src/Neo.Compiler.CSharp/MethodConvert/MethodConvert.cs
  src/Neo.Compiler.CSharp/SequencePointInserter.cs
  src/Neo.SmartContract.Testing/Coverage/Formats/CoberturaFormat.cs
  src/Neo.SmartContract.Testing/Coverage/Formats/CoverletJsonFormat.Models.cs
  src/Neo.SmartContract.Testing/Coverage/Formats/CoverletJsonFormat.cs
  tests/Neo.SmartContract.Template.UnitTests/templates/TestCleanup.cs
Labels: waiting for review
